### ISSUE TITLE
Doctrine -> Update

### ISSUE THREAD

**Issue by vbifial** [mesdt/course#3]
Предлагаю описать, что update принимает 3 параметра: имя таблицы, массив изменяемых ключей, массив первичных ключей.

**Comment by ptz** [comment]
https://github.com/doctrine/dbal/blob/v2.5.1/lib/Doctrine/DBAL/Connection.php#L645

"The update criteria. An associative array containing column-value pairs." -- это про WHERE для UPDATE, **НЕ** про "массив первичных ключей".

**Comment by ptz** [comment]
В общем и целом ход мысли студента понятен, предлагаю обновить пример и методичку

**Comment by smart-frogg** [comment]
https://github.com/mesdt/course/wiki/Cheat-list-Doctrine-DBAL
